#!/bin/sh
#
# @name VTOL MAAL_Tiltrotor
#
# @type VTOL Tiltrotor
#

# 默认配置
. ${R}etc/init.d/rc.vtol_defaults

# 仿真器
PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
# Gazebo世界
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
# 仿真模型
PX4_SIM_MODEL=${PX4_SIM_MODEL:=maal_tiltrotor}

# Gazebo桥接
param set-default SIM_GZ_EN 1 # Gazebo bridge
# 设置MAVlink
param set-default MAV_TYPE 21
# 控制布局
param set-default CA_AIRFRAME 3
# 旋翼布局(FRD坐标系)
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.386
param set-default CA_ROTOR0_PY -0.4
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR1_PX 0.386
param set-default CA_ROTOR1_PY 0.4
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX -0.594
param set-default CA_ROTOR2_PY -0.4
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR3_PX -0.594
param set-default CA_ROTOR3_PY 0.4
param set-default CA_ROTOR3_KM -0.05
# 倾转组
param set-default CA_ROTOR0_TILT 0
param set-default CA_ROTOR1_TILT 0
param set-default CA_ROTOR2_TILT 0
param set-default CA_ROTOR3_TILT 0
param set-default CA_SV_TL0_MAXA 90
param set-default CA_SV_TL0_MINA 0
param set-default CA_SV_TL0_TD 0
param set-default CA_SV_TL0_CT 1
# 控制面组
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS2_TRQ_P 1
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS_COUNT 3
param set-default CA_SV_TL_COUNT 1

# PX4 Motor 端口映射
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
# 电机最小指令
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MIN4 10
# 电机最大指令
param set-default SIM_GZ_EC_MAX1 1100 #1100
param set-default SIM_GZ_EC_MAX2 1100 #1100
param set-default SIM_GZ_EC_MAX3 1100 #1100
param set-default SIM_GZ_EC_MAX4 1100 #1100

# PX4 Servo 端口映射
param set-default SIM_GZ_SV_FUNC1 201 #左外副翼
param set-default SIM_GZ_SV_FUNC2 202 #右外副翼
param set-default SIM_GZ_SV_FUNC3 203 #左内副翼
param set-default SIM_GZ_SV_FUNC4 204 #右内副翼
param set-default SIM_GZ_SV_FUNC5 205 #襟翼左/右
param set-default SIM_GZ_SV_FUNC6 206 #升降舵
param set-default SIM_GZ_SV_FUNC7 207 #方向舵
param set-default SIM_GZ_SV_FUNC8 208 #倾转机构

# 外副翼最大20度，最小-20度
param set-default SIM_GZ_SV_MAXA1 20
param set-default SIM_GZ_SV_MINA1 -20
param set-default SIM_GZ_SV_MAXA2 20
param set-default SIM_GZ_SV_MINA2 -20
# 内副翼最大20度，最小-20度
param set-default SIM_GZ_SV_MAXA3 20
param set-default SIM_GZ_SV_MINA3 -20
param set-default SIM_GZ_SV_MAXA4 20
param set-default SIM_GZ_SV_MINA4 -20
# 襟翼最大20度，最小0度
param set-default SIM_GZ_SV_MAXA5 20
param set-default SIM_GZ_SV_MINA5 0
# 升降舵最大20度，最小-20度
param set-default SIM_GZ_SV_MAXA6 20
param set-default SIM_GZ_SV_MINA6 -20
# 方向舵最大20度，最小-20度
param set-default SIM_GZ_SV_MAXA7 20
param set-default SIM_GZ_SV_MINA7 -20
# 倾转机构最大90度，最小0度
param set-default SIM_GZ_SV_MAXA8 90
param set-default SIM_GZ_SV_MINA8 -90

# 导航
param set-default NPFG_PERIOD 12
# 固定翼控制参数
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_TRIM 0.38
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

# 多旋翼控制参数
param set-default MC_AIRMODE 2


# 大惯量机型增加角速率环，降低姿态环
param set-default MC_ROLLRATE_P 0.4 #0.15 #stable 0.4
param set-default MC_ROLLRATE_I 0.1 #0.2 #stable 0.1
param set-default MC_ROLLRATE_D 0.005 #0.003 #stable 0.005
param set-default MC_PITCHRATE_P 0.4 #0.15 #stable 0.4
param set-default MC_PITCHRATE_I 0.1 #0.2 #stable 0.1
param set-default MC_PITCHRATE_D 0.005 #0.003 #stable 0.005
param set-default MC_YAWRATE_P 0.6 #0.2 #stalbe
param set-default MC_YAWRATE_I 0.15 #0.1 #stable
param set-default MC_YAWRATE_D 0.01 #0 #stable
param set-default MC_ROLL_P 4 #4 #stable 4
param set-default MC_PITCH_P 4 #4 #stable 4
param set-default MC_YAW_P 1.2 #2.8 #stable 2.8


# 位置环参数防止漂移
param set-default MPC_XY_VEL_P_ACC 1.5 #1.8 #stable 1.5
param set-default MPC_XY_VEL_I_ACC 0.5 #0.4 #stable 0.5
param set-default MPC_XY_VEL_D_ACC 0.1 #0.2 #stable 0.1


# 高度环
param set-default MPC_Z_P 1.0 #1.0 #stable 1.0
param set-default MPC_Z_VEL_P_ACC 4.0 #4.0 #stable 4
param set-default MPC_Z_VEL_I_ACC 2 #2 #stable
param set-default MPC_Z_VEL_D_ACC 0.05 #0 #stable 0.05


# 起飞高度
param set-default MIS_TAKEOFF_ALT 15

# 倾转翼控制参数
param set-default VT_FWD_THRUST_EN 0 ###
param set-default VT_FWD_THRUST_SC 0 ###
param set-default VT_TILT_TRANS 0.6
param set-default VT_TYPE 1


